version: '3.8'
services:
  dev-db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5434:5432'
    networks:
      - dev-network
networks:
  dev-network:
